### PR TITLE
Dan dev - Admin:Dashboard and Logout Buttons

### PR DESCRIPTION
**Pull request by dan0x19b**

### CODE REVIEW

**Review by bmeglathery — COMMENTED** [review]
Line 27 of your admin_removeuser.js is not syntactically correct. Also, I'm unsure why you didn't discard the changes to project.properties - we've been doing that all semester now.
I'll approve after you fix your admin_removeuser.js

**Review by dan0x19b — COMMENTED** [review]
The error on line 27 of remove_user.js has been corrected.

**Review by dan0x19b — COMMENTED** [review]
Also I am aware that project.properties should not be here. It was committed by mistake and I do not know how to remove it from the pull request.

**Review by bmeglathery — APPROVED** [review]
Changes are OK 👍

**Pull request merged**
